### ISSUE TITLE
Switching between servers.

### ISSUE THREAD

**Issue by aziz1117** [aluisiora/routeros-client#10]
I have this code to get information from server. But when I switch to the second server still first server remain active and (TotalClients) code bring me data for both servers (one time for the first server and another time for the second server) in each 5 seconds. How I can stop reading from one server and listing just for second server.   
`
const RouterOSClient = require('routeros-client').RouterOSClient
 let api

 serverConnection = (data) => {
    return new RouterOSClient({
        host: data.host,
        user: data.user,
        password: data.password,
        keepalive: true,
        timeout: 50
    })     
}

socket.on('TotalClients', (serverData, status) => {
            if(status == true) {
                api = serverConnection(serverData)
                api.connect().then(client => {
                    client.menu("/ppp secret")
                        .query({ interval: 5 })
                        .stream('print', (err, data) => {
                            if(data.length > 0) io.emit('Clients-Length', data.length)
                        })
                })
            } else {
                if(api) {
                    const closing = api.rosApi.closing
                    if(!closing) api.close()
                }
            }
        })
    })
`

**Comment by aluisiora** [comment]
Are you sure that the first one was disconnected?
Also, this seems like an issue with the logic used in your socket.io, where you are using the same event to send message for two distinct connection, you could try using rooms. But the way it is now, make sure you have disconnected from the previous router by looking at the logs of the router itself, maybe this line is never running:
```javascript
if(status == true) {
    ...
} else {
    if (api) {
        const closing = api.rosApi.closing; // you don't have to check it yourself, the api already does this
        if (!closing) api.close(); // <- this line must run
     }
}
```

**Comment by aziz1117** [comment]
Unfortunately, I reviewed my code there is not mistake. I am sure that routeros does not close once I use routeros.close() even I used console.log(routeros.rosApi.host) after routeros.close(), it shows me server host name. I used also routeros.disconnect(), it's still remain give me server information.

**Comment by aluisiora** [comment]
I`ll try to get a lab running with 2 routeros instances, but I fail to see where the lib might be failing to disconnect.

Have you tried this?
```javascript
if(status == true) {
    ...
} else {
    if (api) {
        api.close();
     }
}
```

**Comment by aziz1117** [comment]
Yes,  api.close() and api.disconnect() does not work, server still remain shows me information after I use these commands.

**Comment by aluisiora** [comment]
I've setup a lab with 2 routeros using chr for testing, adapted your code for the setup and it worked just fine.

Here is a gif of it:
[https://drive.google.com/open?id=1nIKIQqY65NxNkn1ZVH1ccJqUkxMNxZyf](https://drive.google.com/open?id=1nIKIQqY65NxNkn1ZVH1ccJqUkxMNxZyf)

Here is the code I used:
```javascript
const { RouterOSClient } = require("routeros-client");

const serverConnection = (data) => {
    return new RouterOSClient({
        host: data.host,
        user: data.user,
        password: data.password,
        keepalive: true,
        timeout: 50
    });
};

let api;

const totalClients = (serverData, status) => {
    if (status == true) {
        api = serverConnection(serverData);
        api.connect().then(client => {
            console.log(`connected into ${serverData.host}`);

            client.menu("/ppp secret")
                .query({ interval: 2 })
                .stream('print', (err, data) => {
                    if (err) {
                        console.error(err);
                    }

                    if (data.length > 0) {
                        console.info(data.length);
                    }
                });
        });
    } else {
        if (api) {
            api.close().then(() => {
                console.log("disconnected");
            });
        }
    }
}

const server1 = {
    host: '192.168.0.110',
    user: 'admin',
    password: 'admin'
};

const server2 = {
    host: '192.168.0.111',
    user: 'admin',
    password: 'admin'
};

totalClients(server1, true);

setTimeout(() => {
    totalClients(server1, false);
    totalClients(server2, true);

    setTimeout(() => {
        totalClients(server2, false);
    }, 10 * 1000);

}, 10 * 1000);
```

**Comment by aluisiora** [comment]
I've tested with just `node-routeros` and debugged some information, can confirm that, even if the api is disconnecting, the stream won't stop sending data.

**Comment by aluisiora** [comment]
I've issued an update to `node-routeros` that might fix it, try updating to see if that solves this issue.

**Comment by aziz1117** [comment]
Should I use node-routeros instead of routeros-client?

**Comment by aluisiora** [comment]
No, just do an `npm update` and check if the underlying node-routeros gets updated to 1.6.7.

node-routeros is a sub-package of routeros-client.

**Comment by aziz1117** [comment]
Actually, on my app I am using just routeros-client package. I update these package, but still same issue. This is my whole code:
`const RouterOSClient = require('routeros-client').RouterOSClient
require('dotenv').config()
let api

module.exports = (io) => {
    io.on('connection', (socket) => {

        socket.on('StartGetInformation', (serverData, status) => {
            if(status == false) {
                if(api) {
                        api.close()
                }
            } else {
                api = new RouterOSClient({
                    host: serverData.host,
                    user: serverData.user,
                    password: serverData.password,
                    keepalive: true,
                    timeout: 100
                })

                api.connect().then(client => {
                    client.menu("/tool torch")
                        .where({interface: "WAN-1"})
                        .stream((err, packet) => {
                            if(packet.length > 0) {
                                const rxData = packet[0].rx / (1000 * 1000)
                                const rxDataRounded = Math.round(rxData)
                                const txData = packet[0].tx / (1000 * 1000)
                                const txDataRounded = Math.round(txData)
                                const data = {rx:  rxDataRounded, tx: txDataRounded}
                                io.emit('SendSpeedData', data)
                            }
                        })

                    client.menu("/ppp active")
                        .query({ interval: 5 })
                        .stream('print', (err, data) => {
                            if(data.length > 0) {
                                io.emit('Clients-Active', data.length)
                            }
                        })
                
                    client.menu("/ppp secret")
                        .query({ interval: 5 })
                        .stream('print', (err, data) => {if(data.length > 0) io.emit('Clients-Length', data.length)})
                }).catch(err => {
                    console.log(err)
                })
            }
        })
    })

}`

**Comment by aluisiora** [comment]
I see, I may need to force an update through package.json then, `routeros-client` uses `node-routeros` under the hood.

**Comment by aluisiora** [comment]
I've updated `routeros-client` to v1.0.2 which should force `node-routeros` to update too. Could you try it again with those versions?

Edit: `routeros-client` should now be at version `1.1.0`.

**Comment by aziz1117** [comment]
Work perfectly. Thank you.

**Comment by aziz1117** [comment]
At version 1.0.2 work perfectly. But when update to 1.1.0 still give me same issue.

**Comment by aziz1117** [comment]
I noticed that even I use version 1.0.2 it's work perfectly for a while that it shows me same issue after period of time.

**Comment by aziz1117** [comment]
Even at version 1.0.2 which solve the issue, after a while the issue appear again. I do not know, but there is leak somewhere.

**Comment by aziz1117** [comment]
I do not know sometimes work perfectly, and sometimes shows me same issue.
Is it normal if I use api.close() to get inflrmation about server like host.
I use command: console.log(api.rosApi.host) after api.close(), these command shows me host name.

**Comment by aluisiora** [comment]
> I do not know sometimes work perfectly, and sometimes shows me same issue.
> Is it normal if I use api.close() to get inflrmation about server like host.
> I use command: console.log(api.rosApi.host) after api.close(), these command shows me host name.

It is, the routeros information will remain with the "api" object until you don't use it anymore and the garbage collector removes it from memory. This lib will reuse this information to do re-logins and etc.

**Comment by aziz1117** [comment]
Do you have any idea to remove these information and clear "api" object completely from memory.

**Comment by aluisiora** [comment]
To be honest, you shouldn't be using the "rosApi" property since it is [private](https://github.com/aluisiora/routeros-client/blob/c01ba1b2cf0ef8a61d08a87683f0b29256898e5f/src/RosApiMenu.ts#L10).

I really don't understand what is still the issue you are having, after version 1.1.0 of `routeros-client` and version 1.6.6 of `node-routeros`, in my lab with a sample of your code, it worked just fine.
Can you provide any logging information?

**Comment by aluisiora** [comment]
Closing this issue since there was no response from the OP.
