### ISSUE TITLE
speed-test stream 

### ISSUE THREAD

**Issue by woudanator** [aluisiora/routeros-client#11]
Hi guys looking to use the speed-test tool in the API 

I get it to work just fine and returns a array of all the sections of the test but what i would like is to actuality be able to stream the test instead of waiting for the array of elements is this possible 

This is the code i have sofar and like i say it works but ideally i need to open a stream 

`
api.connect().then((client) => {
  cont test = client
    .menu("/tool")
    .exec("speed-test", {
      user: "user",
      password: "pass",
      address: "someip",
    })
    .then((result) => {
      console.log(result);
    });
});`

**Comment by aluisiora** [comment]
There is a builtin feature that merges all sections of the stream and push them to the callback you provide, what you wanna do is skip this merge and receive the data directly?

If so, currently you can't with the routeros-client directly. but you can do it with [node-routeros](https://github.com/aluisiora/node-routeros).

I might change it in a future version.

**Comment by aluisiora** [comment]
Update `1.1.0` (commit 5cdbaf367e47c9ef8e8c2e006ac1af03b595a596) you might be able to do it like this:

```javascript
api.connect().then((client) => {
    cont test = client.menu("/tool")
        .query({
            user: "user",
            password: "pass",
            address: "someip",
        })
        .stream("speed-test");
    
    test.on("data", (rawData) => {
        console.log(rawData);
    });
    
    test.on("error", (rawError) => {
        console.log(rawError);
    });
});
```
This, however, will give you the raw data from routeros, if you want it parsed from the lib, you can do it like this:
```javascript
api.connect().then((client) => {
    cont test = client.menu("/tool")
        .query({
            user: "user",
            password: "pass",
            address: "someip",
        })
        .stream("speed-test");

    test.on("parsed-data", (data) => {
        console.log(data);
    });

    test.on("parsed-error", (error) => {
        console.log(error);
    });
});
```

I'll need to update the documentation for this.

**Comment by woudanator** [comment]
Your second option works perfect love it 

Thanks this is going to help alloy :-)
