### ISSUE TITLE
Cannot connect through VPN

### ISSUE THREAD

**Issue by khertg** [aluisiora/routeros-client#17]
### Code

```javascript
const RouterOSClient = require('routeros-client').RouterOSClient;

const api = new RouterOSClient({
  host: 'https://************:12',
  user: '*****',
  password: '********',
});

api
  .connect()
  .then(async (client) => {
    // Connection successful
    console.log('Connection Successful');

    await api.close();
  })
  .catch((err) => {
    // Got an error while trying to connect
    console.log(err);
  });
```

## Error

```powershell
$ node index.js
RosException
    at Connector.onError (E:\Projects\mikrotek-test\node_modules\node-routeros\dist\connector\Connector.js:176:15)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  name: 'RosException',
  errno: 'ENOTFOUND'
}
```

**Comment by woudanator** [comment]
why are you using HTTPS it won't work as its not a rest API 
in your host, you must add in the IP of the router and if you using a custom API port 
you must add in the port example below 

This works over a VPN as well 

`const api = new RouterOSClient({
       host: "192.168.1.66"
       user:  "admin"
       password: "admin"
       port: 8728
})`

**Comment by khertg** [comment]
@woudanator 
I created a VPN in this site [https://www.hostddns.us/](https://www.hostddns.us/).
Then setup a **ovpn client**  following this guide [https://docs.hostddns.us/docs/vpn-remote/tutorial-mikrotik-ovpn-client/](https://docs.hostddns.us/docs/vpn-remote/tutorial-mikrotik-ovpn-client/)

I can now access the router remotely, 
however when I tried using my vpn url its not working ( base on what you've said ).

Recently I also tried using the IP address of my vpn.
The same thing happened, unable to connect.

```powershell
RosException: Timed out after 10 seconds
    at Connector.onTimeout (E:\Projects\mikrotek-test\node_modules\node-routeros\dist\connector\Connector.js:188:30)
    at Object.onceWrapper (events.js:299:28)
    at Socket.emit (events.js:210:5)
    at Socket._onTimeout (net.js:469:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  name: 'RosException',
  errno: 'SOCKTMOUT',
  message: 'Timed out after 10 seconds'
}
```

**Comment by khertg** [comment]
@woudanator 
Here's what I'm trying to do.

Normally you can connect using **routeros-client** if you are connected locally in the mikrotik router ( **LAN** ).

What I'm trying to setup is to establish a connection remotely ( **WAN** )

**Comment by woudanator** [comment]
have you established that the port is not blocked on the WAN as it might not allow you in via the VPN address due to firewall rules? 

make sure you allow traffic to TCP port 8728

maybe try to use NMAP to see if the router allows you in 

if you have a dynamic IP you would need to implement a resolver in nodejs to resolve the DNS name to an IP before connecting as far as i am aware routeros-client does not have this built-in but I might be wrong 
`

**Comment by woudanator** [comment]
Had a quick look at the DNS service you using and you need to forward traffic from port 8728 on your panel for your DNS so it allows traffic to the router at the moment if you followed the guide you only forwarded port 80 that gives you access to the web interface but not the api

**Comment by khertg** [comment]
I tested 2 VPN for port 80 and 8921.
Now I changed 8921 to 8728.

![image](https://user-images.githubusercontent.com/44987706/121011112-d112f800-c7c8-11eb-9027-462f1fb1c065.png)

The same thing happened cant connect

**Comment by khertg** [comment]
Using local IP

![image](https://user-images.githubusercontent.com/44987706/121011521-4979b900-c7c9-11eb-9825-ad48f7f11c9e.png)

Using the VPN IP

![image](https://user-images.githubusercontent.com/44987706/121011764-9198db80-c7c9-11eb-8f50-0d9be1927fdc.png)

**Comment by woudanator** [comment]
Hi 

It shows the connection is being refused by the router what firewall rules do you have on your router

**Comment by khertg** [comment]
Which router do you mean ?
the ISP router or the Mikrotik router ?
Here are the firewall rules in my mikrotik

![image](https://user-images.githubusercontent.com/44987706/121012893-c5283580-c7ca-11eb-87d4-d725eb2e1069.png)

**Comment by woudanator** [comment]
I 

so you are dropping all invalid traffic that includes 8728 put the following right at top of the table to accept traffic from 8728

do the below rule to allow it and move it to top 

/ip firewall filter add dst-port=8728 protocol=tcp action=accept comment="Allow API Through" chain=input 

see if that helps you

**Comment by khertg** [comment]
@woudanator 
Thank you, you're amazing! 
I can connect now.
Again many thanks.
