### ISSUE TITLE
Stream does not work

### ISSUE THREAD

**Issue by aziz1117** [aluisiora/routeros-client#4]
Hi, I wrote this code to get Tx-Packets and Rx-Packets.

const RouterOSClient = require('routeros-client').RouterOSClient
const api = new RouterOSClient({
    host: process.env.SERVER_HOST,
    user: process.env.SERVER_USER,
    password: process.env.SERVER_PASSWORD,
    keepalive: true
})

api.connect().then(client => {
    const torchMenu = client.menu("/tool torch")
        .where({interface: "WAN-1"})
        .stream((err, data) => {
            if (err) console.log(err)
            console.log(data)
        })
})

This code shows error:
TypeError: this.debounceSendingEmptyData is not a function.

Could you please help me to solve this issue.

**Comment by aluisiora** [comment]
Sorry, that was a problem upstream with `node-routeros`. I've updated with a fix, run `npm update` and let me know if it's working for you now.

**Comment by aziz1117** [comment]
It's work perfectly. Thank you.
