### ISSUE TITLE
cant get /interface/wireless/monitor Information

### ISSUE THREAD

**Issue by woudanator** [aluisiora/routeros-client#9]
Hi This is more a question than an issue 

I need to pull the interface CCQ I use to do this via php_api but now a use node 
so id like to move away from the PHP if I can 

Is it at all possible to get the information from 

menu('/interface/wireless/monitor') or something in that line allmost :-) 

I try doing this using node-routeros as well can't seem to be able to get it there is either

**Comment by ramwolken9** [comment]
Hi @woudanator 
You can use the below sample code to steam interface monitor Information form device
```
client.menu("/interface wireless").query({ interval: interval, numbers: ether1,ether2'})
.stream('monitor', ((err, data) => {
if (err) {
console.log(err)
}else{
console.log(data)
}}));
```

**Comment by aluisiora** [comment]
As @ramwolken9 said, you should use the [stream](https://github.com/aluisiora/routeros-client/wiki/Streaming-Content) method for that.

Let me know if that helps you.

**Comment by woudanator** [comment]
Hi @ramwolken9 and @aluisiora 

It worked perfectly I was trying to avoid streams but I can work around that using a timeout function 

One last thing how do a apply actions for example firmware updates to the router :-)
or check for software updates in the "system packages update" menu  

We doing some automation and I can't see an obvious way of doing this in the wiki 

Your assistance is much appreciated

**Comment by aluisiora** [comment]
I had to do it once many years ago when there was no "system packages update" available on the menu. The way I ended up doing was uploading the new version through sftp and then using the api to reboot the router. There may be optimal ways nowadays.

**Comment by aluisiora** [comment]
Closing this since the issue was solved.
